#!/bin/bash
#
# test_funcs_generated.sh - Auto-generated tests from function documentation
# Generated by tools/gen_docs.sh
#

SC="${SC:-./bin/sc}"
PASS=0
FAIL=0

test_expr() {
    local result
    result=$("$SC" "$1" 2>&1 | head -1)
    if [ $? -eq 0 ] && ! echo "$result" | grep -qi "error"; then
        PASS=$((PASS + 1))
    else
        echo "  FAIL: $1 -> $result"
        FAIL=$((FAIL + 1))
    fi
}

test_exact() {
    local result expected="$2"
    result=$("$SC" "$1" 2>&1 | head -1)
    # Handle boolean true/false vs 1/0
    case "$result" in
        true) result=1 ;;
        false) result=0 ;;
    esac
    if [ "$result" = "$expected" ] || echo "$result" | grep -qE "^= ?$expected$"; then
        PASS=$((PASS + 1))
    else
        echo "  FAIL: $1 = '$result' (expected '$expected')"
        FAIL=$((FAIL + 1))
    fi
}

# Approximate comparison for floats
test_approx() {
    local result expected="$2" tol="${3:-0.0001}"
    result=$("$SC" "$1" 2>&1 | head -1)
    
    # Check for error
    if echo "$result" | grep -qi "error"; then
        echo "  FAIL: $1 -> $result"
        FAIL=$((FAIL + 1))
        return
    fi
    
    # Strip = prefix
    result=$(echo "$result" | sed 's/^= //')
    
    # Compare numerically using bc
    if command -v bc >/dev/null 2>&1; then
        local diff
        diff=$(echo "scale=10; x=$result - ($expected); if(x<0) -x else x" | bc 2>/dev/null)
        if [ -n "$diff" ] && echo "$diff < $tol" | bc -l 2>/dev/null | grep -q 1; then
            PASS=$((PASS + 1))
            return
        fi
    fi
    
    # Fallback: check if starts with expected
    if echo "$result" | grep -q "^$expected"; then
        PASS=$((PASS + 1))
    else
        echo "  FAIL: $1 = '$result' (expected ~$expected)"
        FAIL=$((FAIL + 1))
    fi
}

echo "=== GENERATED FUNCTION TESTS ==="
echo ""

echo "Testing: complex"
test_exact "re(3+4i)" "3"
test_exact "real(3+4i)" "3"
test_exact "im(3+4i)" "4"
test_exact "imag(3+4i)" "4"
test_expr "conj(3+4i)"
test_exact "abs(-5)" "5"
test_exact "arg(1)" "0"
test_exact "angle(1)" "0"
test_exact "phase(1)" "0"
test_expr "complex(3, 4)"

echo "Testing: dispatch"

echo "Testing: exp"
test_exact "exp(0)" "1"
test_exact "exp2(0)" "1"
test_exact "expm1(0)" "0"
test_exact "pow2(8)" "256"
test_exact "sqrt(4)" "2"
test_exact "cbrt(8)" "2"
test_exact "nthroot(16, 4)" "2"
test_exact "hypot(3, 4)" "5"
test_exact "realsqrt(4)" "2"
test_exact "realpow(2, 3)" "8"
test_exact "ln(1)" "0"
test_exact "log(1)" "0"
test_exact "log10(1)" "0"
test_exact "log2(1)" "0"
test_exact "log1p(0)" "0"
test_exact "logb(8, 2)" "3"
test_exact "reallog(1)" "0"

echo "Testing: linalg"
test_exact "trace(eye(5))" "5"
test_exact "cond(eye(3))" "1"
test_exact "norm([3,4])" "5"

echo "Testing: matrix"
test_exact "dot([1,2,3], [4,5,6])" "32"
test_exact "length([1,2,3])" "3"
test_exact "rows([1,2,3])" "1"
test_exact "cols([1,2,3])" "3"
test_exact "numel([1,2,3])" "3"
test_exact "ndims([1,2,3])" "2"
test_exact "isempty([])" "1"
test_exact "isscalar(5)" "1"
test_exact "isvector([1,2,3])" "1"
test_exact "isrow([1,2,3])" "1"
test_exact "issquare(eye(3))" "1"
test_exact "issorted([1,2,3,4])" "1"
test_exact "nnz([1,0,2,0,3])" "3"

echo "Testing: misc"
test_approx "trapz([1,2,3,4])" "7.5"
test_exact "polyval([1,0,-2], 2)" "2"
test_approx "deg2rad(180)" "3.1416"
test_exact "rad2deg(pi)" "180"
test_approx "wrapToPi(4)" "0.8584"
test_exact "wrap180(270)" "-90"
test_exact "wrap360(-90)" "270"
test_exact "wrapTo180(270)" "-90"
test_exact "wrapTo360(-90)" "270"
test_exact "any([0,0,1,0])" "1"
test_exact "all([1,2,3,4])" "1"
test_exact "eq(3, 3)" "1"
test_exact "ne(3, 4)" "1"
test_exact "lt(3, 4)" "1"
test_exact "le(3, 3)" "1"
test_exact "gt(4, 3)" "1"
test_exact "ge(3, 3)" "1"
test_exact "isnan(0/0)" "1"
test_exact "isinf(1/0)" "1"
test_exact "isfinite(5)" "1"
test_exact "isreal(5)" "1"
test_exact "bitand(12, 10)" "8"
test_exact "bitor(12, 10)" "14"
test_exact "bitxor(12, 10)" "6"
test_exact "bnot(0)" "-1"
test_exact "bitshift(1, 4)" "16"
test_exact "shl(1, 8)" "256"
test_exact "shr(256, 8)" "1"
test_exact "nextpow2(5)" "3"
test_approx "pi" "3.1416"
test_approx "e" "2.7183"
test_exact "i^2" "-1"
test_approx "phi" "1.618"
test_approx "golden" "1.618"
test_approx "tau" "6.2832"
test_exact "1/0" "Inf"
test_exact "0/0" "NaN"

echo "Testing: number"
test_exact "gcd(12, 8)" "4"
test_exact "lcm(4, 6)" "12"
test_exact "isprime(2)" "1"
test_exact "nextprime(10)" "11"
test_exact "prevprime(10)" "7"
test_exact "primepi(10)" "4"
test_exact "nthprime(1)" "2"
test_exact "fact(0)" "1"
test_exact "factorial(5)" "120"
test_exact "factorial2(5)" "15"
test_exact "ncr(5, 2)" "10"
test_exact "npr(5, 2)" "20"
test_exact "comb(5, 2)" "10"
test_exact "perm(5, 2)" "20"
test_exact "fibonacci(0)" "0"
test_exact "lucas(0)" "2"
test_exact "catalan(0)" "1"
test_exact "divisors(12)" "6"
test_exact "divisorsum(12)" "28"
test_exact "totient(1)" "1"
test_exact "eulerphi(10)" "4"
test_exact "mobius(1)" "1"
test_exact "even(4)" "1"
test_exact "odd(7)" "1"
test_exact "ndigits(123)" "3"
test_exact "digitsum(123)" "6"
test_exact "digitroot(123)" "6"
test_exact "isperfect(6)" "1"
test_exact "isabundant(12)" "1"
test_exact "isdeficient(8)" "1"
test_exact "issquarefree(6)" "1"

echo "Testing: round"
test_exact "floor(3.7)" "3"
test_exact "ceil(3.2)" "4"
test_exact "round(3.4)" "3"
test_exact "trunc(3.7)" "3"
test_exact "fix(3.7)" "3"
test_approx "frac(3.7)" "0.7"
test_exact "sign(-5)" "-1"
test_exact "signum(-5)" "-1"
test_exact "mod(17, 5)" "2"
test_exact "rem(17, 5)" "2"
test_exact "clamp(5, 0, 10)" "5"
test_exact "clip(5, 0, 10)" "5"

echo "Testing: special"
test_exact "gamma(5)" "24"
test_approx "lgamma(5)" "3.1781"
test_exact "tgamma(5)" "24"
test_approx "beta(2, 3)" "0.0833"
test_approx "digamma(1)" "-0.5772"
test_approx "psi(1)" "-0.5772"
test_exact "erf(0)" "0"
test_exact "erfc(0)" "1"
test_exact "besselj(0, 0)" "1"
test_approx "bessely(0, 1)" "0.0883"
test_approx "zeta(2)" "1.6449"
test_exact "harmonic(1)" "1"
test_approx "sigmoid(0)" "0.5"
test_approx "softplus(0)" "0.6931"
test_exact "heaviside(-1)" "0"
test_exact "step(-1)" "0"
test_exact "rect(0)" "1"
test_exact "tri(0)" "1"

echo "Testing: stats"
test_exact "sum([1,2,3,4,5])" "15"
test_exact "prod([1,2,3,4,5])" "120"
test_exact "mean([1,2,3,4,5])" "3"
test_exact "median([1,2,3,4,5])" "3"
test_exact "mode([1,2,2,3])" "2"
test_approx "std([1,2,3,4,5])" "1.5811"
test_approx "var([1,2,3,4,5])" "2.5"
test_exact "min([3,1,4,1,5])" "1"
test_exact "max([3,1,4,1,5])" "5"
test_exact "range([1,2,3,4,5])" "4"
test_approx "geomean([1,2,4,8])" "2.8284"
test_approx "harmmean([1,2,4])" "1.7143"
test_exact "skewness([1,2,3,4,5])" "0"
test_approx "kurtosis([1,2,3,4,5])" "1.7"
test_approx "mad([1,2,3,4,5])" "1.2"
test_exact "iqr([1,2,3,4,5,6,7])" "4"
test_approx "rms([1,2,3])" "2.1602"
test_exact "sumsq([1,2,3])" "14"
test_approx "meansq([1,2,3])" "4.6667"
test_approx "prctile([1:10], 50)" "5.5"
test_approx "cov([1,2,3,4,5])" "2.5"
test_approx "normpdf(0)" "0.3989"
test_approx "normcdf(0)" "0.5"
test_exact "norminv(0.5)" "0"
test_approx "tcdf(0, 10)" "0.5"
test_exact "chi2cdf(0, 5)" "0"

echo "Testing: trig"
test_exact "sin(0)" "0"
test_exact "cos(0)" "1"
test_exact "tan(0)" "0"
test_exact "asin(0)" "0"
test_exact "acos(1)" "0"
test_exact "atan(0)" "0"
test_exact "atan2(0, 1)" "0"
test_exact "sinh(0)" "0"
test_exact "cosh(0)" "1"
test_exact "tanh(0)" "0"
test_exact "asinh(0)" "0"
test_exact "acosh(1)" "0"
test_exact "atanh(0)" "0"
test_exact "sec(0)" "1"
test_exact "csc(pi/2)" "1"
test_exact "cot(pi/4)" "1"
test_exact "asec(1)" "0"
test_approx "acsc(1)" "1.5708"
test_approx "acot(1)" "0.7854"
test_exact "sech(0)" "1"
test_approx "csch(1)" "0.8509"
test_approx "coth(1)" "1.3130"
test_exact "asech(1)" "0"
test_approx "acsch(1)" "0.8814"
test_approx "acoth(2)" "0.5493"
test_exact "sind(0)" "0"
test_exact "cosd(0)" "1"
test_exact "tand(0)" "0"
test_exact "asind(0)" "0"
test_exact "acosd(1)" "0"
test_exact "atand(0)" "0"
test_exact "atan2d(0, 1)" "0"
test_exact "sinc(0)" "1"
test_exact "sinpi(0)" "0"
test_exact "cospi(0)" "1"

echo ""
echo "=== RESULTS: $PASS passed, $FAIL failed ==="
[ $FAIL -eq 0 ]
